# SPDX-License-Identifier: GPL-2.0
#
# Makefile for ReKernel-X
#

rekernel_x-y := rkx.o \
		rkx_genl.o \
		rkx_netuid.o \
		rkx_free_async.o \
		rkx_frozen.o \
		rkx_binder.o \
		rkx_signal.o \
		rkx_netfilter.o \
		rkx_binder_kp.o \
		rkx_binder_alloc.o

obj-$(CONFIG_REKERNEL_X) += rekernel_x.o
